### ISSUE TITLE
make it watch or recheck for current info

### ISSUE THREAD

**Issue by antonytrupe** [fewieden/MMM-ip#12]
Sometimes my pi gets disconnected from a network and when it reconnects it gets a new ip address, but the old one stays displayed. Maybe add some way to configure a time interval to recheck the current network info and update the display, default to never recheck.

Thoughts?

**Comment by fewieden** [comment]
@antonytrupe the new release has a config option to regularly update the network interfaces https://github.com/fewieden/MMM-ip/releases/tag/2.1.0
