### ISSUE TITLE
config file error

### ISSUE THREAD

**Issue by DNA2010** [fewieden/MMM-ip#4]
had to comment out the config to make it work
is there a way to make the display brighter and bigger on the screen
is there samples codes of using the options
thanks
{
    module: 'MMM-ip',
    position: 'bottom_right',
    //config: {  ... }
}

**Comment by jsteel715** [comment]
My config that works:

{
    module: "MMM-ip",
    position: "top_right",
   config: {
        voice: false,
        startHidden: false
   }
}

**Comment by fewieden** [comment]
@DNA2010 it looks like you used some wrong quotes.

1. is there a way to make the display brighter?
  - the config option `dimmed` is meant to do that

2. is there a way to make the display bigger?
  - the config option `fontSize` is meant to do that

3. is there samples codes of using the options

```js
{
    module: 'MMM-ip',
    position: 'bottom_right',
    config: {
        fontSize: 20,
        dimmed: false
    }
}
```

**Comment by stampeder** [comment]
No control over location, font size, or title. Here is my config.js portion:
{
                        module: "MMM-ip",
                        position: "top_right",
                        config: {
                                fontsize: "5",
                                dimmed: "true",
                                showFamily: "IPv4",
                                showType: "both",
                                voice: "false",
                                startHidden: "false"
                        }
                },
What does appear is in the center of the screen.
Thanks.
Glenn.

**Comment by stampeder** [comment]
Please ignore. It now work perfectly. Needed quotes around values and not around booleans.
Very happy it works well.
