### ISSUE TITLE
Often get module "loading"

### ISSUE THREAD

**Issue by roccodicarlo** [fewieden/MMM-ip#5]
I often get the module just displaying "LOADING" .  It doesn't seem to retry.  I may have to restart MM once or twice to get it to display the IP address. Is there a way for the module to retry every 15 minutes if it doesn't get response?

**Comment by fewieden** [comment]
@roccodicarlo can you provide any error message (terminal and dev tools) when it states loading?

**Comment by fewieden** [comment]
Closing due to lack of information
