### ISSUE TITLE
Interface information isn't showing as a modal when startHidden = false

### ISSUE THREAD

**Issue by mattmillerai** [fewieden/MMM-ip#7]
I'm not sure if this is intended behavior but this is what it looks like when startHidden is false (default):

<img width="1312" alt="Screen Shot 2020-10-11 at 11 58 01 PM" src="https://user-images.githubusercontent.com/7741082/95714790-98ad2100-0c1d-11eb-8b5c-f96aae5c8ee3.png">

It's just text on the page. If this is supposed to appear as a modal then the MMM-ip-blur class would just need to show on all other modules on load potentially?

**Comment by fewieden** [comment]
@MillerMedia this should not happen. I rewrote the modal behavior by integrating MMM-Modal instead here https://github.com/fewieden/MMM-ip/pull/8
